name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Replace with your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and export static files
        run: |
          docker build -t astro-build .
          docker create --name extract astro-build
          docker cp extract:/output ./dist
          docker rm extract

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
